document.addEventListener("DOMContentLoaded", function () {
    var addEmployeeButton = document.getElementById("add-employee-button");
    var infoEmployeeSection = document.querySelector(".info-employee");
    // Fonction pour gérer le clic sur le bouton "Ajouter un employé"
    function handleAddEmployeeClick(event) {
        event.preventDefault(); // Pour éviter le comportement par défaut du bouton (rechargement de la page)
        // Construction du formulaire à afficher dans la section info-employee
        var formHTML = "\n            <form action=\"#\" method=\"POST\">\n                <h2>Ajouter un employ\u00E9 : \n                    <input type=\"submit\" value=\"Confirmer l'ajout\">\n                </h2>\n                <fieldset>\n                    <legend>INFORMATIONS</legend>\n                    <div class=\"line-input\">\n                        <div class=\"input-container\">\n                            <label for=\"nom\">Nom :</label>\n                            <input type=\"text\" id=\"nom\" name=\"nom\" required>\n                        </div>\n                    \n                        <div class=\"input-container\">\n                            <label for=\"prenom\">Pr\u00E9nom :</label>\n                            <input type=\"text\" id=\"prenom\" name=\"prenom\" required>\n                        </div>\n                    </div>\n                    \n                    <div class=\"line-input\">\n                        <div class=\"input-container\">\n                            <label for=\"tel\">Num\u00E9ro de t\u00E9l\u00E9phone :</label>\n                            <input type=\"tel\" id=\"tel\" name=\"tel\" required>\n                        </div>\n                    \n                        <div class=\"input-container\">\n                            <label for=\"email\">Adresse email :</label>\n                            <input type=\"email\" id=\"email\" name=\"email\" required>\n                        </div>\n                    </div>\n                    \n                    <div class=\"line-input\">\n                        <div class=\"input-container\">\n                            <label for=\"adresse\">Adresse :</label>\n                            <textarea id=\"adresse\" name=\"adresse\" rows=\"4\" required></textarea>\n                        </div>\n                    </div>\n                    \n                    <br><br>\n                </fieldset>\n        \n                <fieldset>\n                    <legend>POSTE</legend>\n                    <div class=\"line-input\">\n                        <div class=\"input-container\">\n                            <label for=\"poste\">Poste :</label>\n                            <input type=\"text\" id=\"poste\" name=\"poste\" required><br><br>\n                        </div>\n                        <div class=\"input-container\">\n                            <label for=\"rang\">Rang :</label>\n                            <input type=\"text\" id=\"rang\" name=\"rang\" required><br><br>\n                        </div>\n                    </div>\n                </fieldset>\n            </form>\n        ";
        // Affichage du formulaire dans la section info-employee
        infoEmployeeSection.innerHTML = formHTML;
    }
    // Ajout de l'écouteur d'événement sur le clic du bouton "Ajouter un employé"
    addEmployeeButton.addEventListener("click", handleAddEmployeeClick);
});
